---
image:
  file: .gitpod.Dockerfile

tasks:
- name: R and Python setup
  before: |
    make gitpod-before
  init: |
    make gitpod-init
  command: |
    make gitpod-command

ports:
  - port: 8787
    onOpen: open-browser
  - port: 3000-8786
    onOpen: ignore
  - port: 8786-15000
    onOpen: ignore

vscode:
  extensions:
    - bungcip.better-toml
    - eamodio.gitlens
    - james-yu.latex-workshop
    - ms-python.isort
    - ms-python.python
    - RDebugger.r-debugger
    - reditorsupport.r
    - sourcery.sourcery
    - streetsidesoftware.code-spell-checker
