image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      pip3 install -r requirements.txt
      make dataset

  - command: |
      echo 'eval "$(starship init bash)"' >> $HOME/.bashrc
      sudo bash -c "echo 'setwd(\"/workspace/atlanta-shore\")' >> /home/gitpod/.Rprofile"
      sudo usermod --password $(openssl passwd -1 $RSTUDIO_PASSWORD) gitpod
      sudo rstudio-server start

ports:
  - port: 8787
    onOpen: open-browser
  - port: 3000-8786
    onOpen: ignore
  - port: 8786-15000
    onOpen: ignore

vscode:
  extensions:
    - eamodio.gitlens
    - streetsidesoftware.code-spell-checker
    - ms-python.python
    - Ikuyadeu.r
