---
image:
  file: .gitpod.Dockerfile

tasks:
- name: R and Python setup
  init: |
    mkdir -p .R/library
    make requirements
  command: |
    sudo bash -c "echo R_LIBS_USER=$GITPOD_REPO_ROOT/.R/library > /home/gitpod/.Renviron"
    ln -s /workspace/atlanta-shore /home/gitpod/atlanta-shore
    # https://stackoverflow.com/questions/47541007/how-to-i-bypass-the-login-page-on-rstudio
    sudo usermod -a -G sudo gitpod
    sudo bash -c "echo 'server-user=gitpod' >> /etc/rstudio/rserver.conf"
    sudo bash -c "echo 'auth-none=1' >> /etc/rstudio/rserver.conf"
    # Restart the rserver with sudo otherwise it won't run for the gitpod user (dunno why)
    sudo rserver
    sudo pkill rserver
    alias python='python3'
    # Add /home/gitpod/bin to the path so TinyTex can be found.
    sudo bash -c "echo 'export DOTPROFILE=yes' >> /home/gitpod/.profile"
    sudo bash -c "echo 'export PATH=$PATH:/home/gitpod/bin' >> /home/gitpod/.profile"

ports:
  - port: 8787
    onOpen: open-browser
  - port: 3000-8786
    onOpen: ignore
  - port: 8786-15000
    onOpen: ignore

vscode:
  extensions:
    - bungcip.better-toml
    - eamodio.gitlens
    - james-yu.latex-workshop
    - ms-python.isort
    - ms-python.python
    - RDebugger.r-debugger
    - reditorsupport.r
    - sourcery.sourcery
    - streetsidesoftware.code-spell-checker
