image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      pip3 install -r requirements.txt
      curl -fsSL https://starship.rs/install.sh | bash -s -- --yes
      echo 'eval "$(starship init bash)"' >> $HOME/.bashrc
      source $HOME/.bashrc

    command: make dataset

  - name: LaTeX auto-rebuild
    command: >
      while find . -name '*.tex' | xargs inotifywait -qqre modify .; do \
        latexmk -pdf ; \
      done

vscode:
  extensions:
    - james-yu.latex-workshop
    - ikuyadeu.r