image:
  file: .gitpod.Dockerfile


tasks:
  # The python modules survive a restart because they are in the user director
  # The data
  - init: |
      pip3 install -r requirements.txt
      make dataset

    command: |
      sudo usermod -a -G rstudio-users gitpod
      sudo usermod -a -G staff gitpod
      sudo mkdir -p /workspace/R/library
      Rscript requirements.r
      echo 'eval "$(starship init bash)"' >> $HOME/.bashrc
      sudo usermod --password $(openssl passwd -1 $RSTUDIO_PASSWORD) gitpod
      sudo rstudio-server restart

ports:
  - port: 8787
    onOpen: open-browser
  - port: 3000-8786
    onOpen: ignore
  - port: 8786-15000
    onOpen: ignore

vscode:
  extensions:
    - eamodio.gitlens
    - streetsidesoftware.code-spell-checker
    - ms-python.python
    - Ikuyadeu.r
