image:
  file: .gitpod.Dockerfile

tasks:
  # Ensure that the Python Modules and R packages are installed.
  - init: |
      python -m pip install virtualenv
      virtualenv .venv
      source .venv/bin/activate
      pip install -r requirements.txt
      make dataset
      Rscript requirements.r
  # Start up the rstudio-server with permissions for the `gitpod` user. 
    command: |
      echo 'eval "$(starship init bash)"' >> $HOME/.bashrc
      source $HOME/.bashrc
      source .venv/bin/activate
      sudo bash -c "echo R_LIBS_USER=$GITPOD_REPO_ROOT/.R/library > /home/gitpod/.Renviron"
      sudo bash -c "echo 'setwd(\"$GITPOD_REPO_ROOT\")' > /home/gitpod/.Rprofile"
      sudo usermod -a -G rstudio-users gitpod
      sudo usermod --password $(openssl passwd -1 $RSTUDIO_PASSWORD) gitpod
      sudo rstudio-server restart

ports:
  - port: 8787
    onOpen: open-browser
  - port: 3000-8786
    onOpen: ignore
  - port: 8786-15000
    onOpen: ignore

vscode:
  extensions:
    - eamodio.gitlens
    - streetsidesoftware.code-spell-checker
    - ms-python.python
    - Ikuyadeu.r
