---
image:
  file: .gitpod.Dockerfile

tasks:
  - name: R and Python setup
    before: | # Preparatory steps that should run before the main setup, such as setting up tools.
      make gitpod-before
    init: | # Tasks for setting up the project, like downloading dependencies.
      make gitpod-init
    command: | # Commands that start your main application or services.
      make gitpod-command

ports:
  - port: 8787
    onOpen: open-browser
  - port: 3000-8786
    onOpen: ignore
  - port: 8786-15000
    onOpen: ignore

vscode:
  extensions:
    - bierner.markdown-mermaid
    - charliermarsh.ruff
    - eamodio.gitlens
    - james-yu.latex-workshop
    - ms-python.black-formatter
    - ms-python.isort
    - ms-python.mypy-type-checker
    - ms-python.pylint
    - ms-python.python
    - RDebugger.r-debugger
    - reditorsupport.r
    - streetsidesoftware.code-spell-checker
    - tamasfe.even-better-toml
