# SITE CONFIGURATION
title: Beavers and Botany
url: https://joejcollins.github.io
baseurl: /atlanta-shore # the sub path of your site, e.g. /blog/

remote_theme: just-the-docs/just-the-docs
search_enabled: true
mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "9.1.3"
