# SITE CONFIGURATION

url: https://joejcollins.github.io/
baseurl: /blog/atlanta-shore # the sub path of your site, e.g. /blog/

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: Beavers and Botany

timezone: Europe/London
