# SITE CONFIGURATION
baseurl: "" # the sub path of your site, e.g. /blog/
url: "0.0.0.0" # the base hostname & protocol for your site

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: Beavers and Botany

timezone: Europe/London
