---
name: Python and R Tests

on:
  push:
    branches: [ main ]

jobs:
  run_python_tests:
    runs-on: ubuntu-latest
    container:
      image: rocker/verse:4.3.2
    env:
      GITHUB_PAT: ${{ secrets.PAT_NO_PERMISSIONS }}
    steps:
      - name: Checkout the repo.
        uses: actions/checkout@v4
        with:
          submodules: true
          clean: true
      - name: Install Python.
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Create the virtual environment and run tests.
        run: |
          echo $GITHUB_PAT
          make gitpod-before
          make gitpod-init
          make test

