---
name: Python Tests

on:
  pull_request:
    branches: [master]

jobs:
  run_python_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo.
        uses: actions/checkout@v4
        with:
          submodules: true
          clean: true
      - uses: actions/setup-python@v2
        with:
          python-version: 3.11
