---
name: Run the Python and R Tests

on:
  push:
    branches: [ main ]

jobs:
  run_python_tests:
    runs-on: ubuntu-latest
    container:
      image: joejcollins/atlanta-shore:latest
    env:
      GITHUB_PAT: ${{ secrets.PAT_NO_PERMISSIONS }}
    steps:
      - name: Checkout the repo without the Github action because it does not work on the container.
        uses: actions/checkout@v4
        with:
          submodules: false
          clean: true
      - name: Create the virtual environment and run tests.
        run: |
          echo $GITHUB_PAT
          make gitpod-before
          make gitpod-init
          make report
          make test

