---
name: Run the Python and R Tests

on:
  push:
    branches: [ main ]

jobs:
  run_python_tests:
    runs-on: ubuntu-latest
    container:
      image: joejcollins/atlanta-shore:latest
      options: --user root # needs to be root or the checkout fails.
    env:
      GITHUB_PAT: ${{ secrets.PAT_NO_PERMISSIONS }}
    steps:
      - name: Checkout the repo (ensuring the user is root ^^^ or it fails).
        uses: actions/checkout@v4
        with:
          submodules: false
          clean: true
      - name: Create the virtual environment and run tests.
        run: |
          echo $GITHUB_PAT
          export GITPOD_REPO_ROOT="$(pwd)"
          make gitpod-before
          make gitpod-init
          cat ~/.Rprofile
          cat ~/.Renviron
          make report
          make test

